function [remaining, expired] = remainingPdbSlots(pdbMs, genSlot, currentSlot, mu)
%remainingPdbSlots Packet delay budget still available at a slot, in slots.
%Spec:   the PDB itself is TS 23.287 clause 5.4.4 Table 5.4.4-1 (PC5 QoS characteristics),
%        surfaced by +cfg/pqiTable as PDB_ms. How much of it is left, and what to do when
%        none is, are not specified anywhere -- clause 8.1.4 only consumes "the remaining
%        packet delay budget" as a given. Hence non-normative, hence here.
%Inputs: pdbMs        real, >0 -- the flow's packet delay budget in ms (pqiTable's PDB_ms)
%        genSlot      integer, >=0 -- slot in which the packet was generated by +app/. The
%                     reference point for D_app per +app/CLAUDE.md: the budget is measured
%                     from creation, not from arrival at MAC.
%        currentSlot  integer, >= genSlot -- the slot being evaluated
%        mu           integer, 0..3 -- mu_SL, the SCS configuration of the SL BWP
%Outputs: remaining  integer, >=0 -- budget left in **PHYSICAL** slots, clamped at 0. Physical
%                    because a delay budget is wall clock. It must be converted to logical
%                    pool slots by phy.rx.policy.pdbLogicalSlots before it can bound T2, which
%                    is an offset in clause 8.1.4's pool-slot numbering. The two coincide only
%                    on a pool that holds every slot.
%         expired    logical -- true when the budget is exhausted. The caller must DISCARD the
%                    SDU on this, not transmit it late.
%
%Why `expired` is a separate output and not just `remaining == 0`: the discard is the point.
%A packet allowed to transmit past its PDB is counted as a very slow success, when what
%actually happened is a loss. That single confusion inflates throughput and truncates the
%latency tail at the same time, in the same direction, so nothing downstream contradicts it.
%The budget must be tested here, once, and acted on by the caller.
%
%Slots, not ms, because every window in clause 8.1.4 is in slots and the conversion is
%numerology-dependent (x2^mu). floor(), not round(), since a partially-elapsed slot is not
%usable: the budget covers whole transmission opportunities.

if ~(pdbMs > 0)
    error('policy:remainingPdbSlots:badPdb', 'remainingPdbSlots: pdbMs must be > 0, got %s', num2str(pdbMs));
end
if ~(mu >= 0 && mu <= 3 && mod(mu, 1) == 0)
    error('policy:remainingPdbSlots:badMu', 'remainingPdbSlots: mu must be an integer in 0..3, got %s', num2str(mu));
end
if mod(genSlot, 1) ~= 0 || mod(currentSlot, 1) ~= 0
    error('policy:remainingPdbSlots:badSlot', 'remainingPdbSlots: genSlot and currentSlot must be integers');
end
if currentSlot < genSlot
    error('policy:remainingPdbSlots:negativeAge', 'remainingPdbSlots: currentSlot (%s) precedes genSlot (%s)', num2str(currentSlot), num2str(genSlot));
end

pdbSlots  = floor(pdbMs * 2^mu);          % ms -> slots at this numerology
elapsed   = currentSlot - genSlot;
remaining = max(0, pdbSlots - elapsed);
expired   = (remaining == 0);
end
