function setupPaths(~)
%setupPaths Add all nrv2x-matlab directories to the path.
%   The tree is self-contained: the Version 3 parts worth keeping were
%   migrated here (Plan.md §18) and the old tree removed.
%
%     config/       preconfiguration, slot map, tables
%     phy/          5G Toolbox sidelink chain (pool, PSCCH/PSSCH/SL-SCH,
%                   SCI codec, DM-RS, MCS/TBS, TRIV/FRIV, power control)
%     phy/sensing/  TS 38.214 8.1.4 sensing + candidate selection
%     mac/          MAC entity (SPS, triggers, re-eval/pre-emption), HARQ
%     channel/      TR 38.901 RMa pathloss, TDL fading, UE channel graph
%     l2/           RLC UM/AM, PDCP, SDAP (upper layers, M2 scope)
%     app/          ETSI CAM/DENM, SAE, PC5-S traffic sources
%     rf/           23 dBm analog-equivalent transmitter
%     tests/        unit + integration + visualization tests

root = fileparts(mfilename('fullpath'));
addpath(root, ...
    fullfile(root, 'config'), ...
    fullfile(root, 'phy'), ...
    fullfile(root, 'phy', 'sensing'), ...
    fullfile(root, 'mac'), ...
    fullfile(root, 'channel'), ...
    fullfile(root, 'l2'), ...
    fullfile(root, 'app'), ...
    fullfile(root, 'rf'), ...
    fullfile(root, 'tests'));
end
