function [timingOffset, NID2, peak, corrProfile] = pssSearch(waveform, mu, nSubcarriers, searchLen)
%pssSearch Acquire slot timing and N_ID,2^SL by correlating against both S-PSS sequences.
%Spec:   none -- acquisition is not specified. TS 38.211 clause 8.4.2.1 defines the S-PSS this
%        correlates against; how a receiver finds it is where a vendor differentiates, which is
%        why +phy/+rx/CLAUDE.md places it here.
%Inputs: waveform      nSamples-by-1 complex column -- received baseband samples, NOT yet
%                      time-aligned. That is the whole point: phy.lib.ofdmDemod assumes
%                      alignment and says so, and a demodulator that searched for its own
%                      timing would hide every synchronisation failure inside a channel
%                      estimation error
%        mu            integer, 0..3 -- mu_SL
%        nSubcarriers  integer -- the grid width the S-SSB sits in
%        searchLen     integer, >=1 -- how many sample offsets to test, starting from 0
%Outputs: timingOffset  integer, 0..searchLen-1 -- the offset whose correlation peaked
%         NID2          integer, 0 or 1 -- the S-PSS hypothesis that won
%         peak          real -- the winning normalised correlation magnitude
%         corrProfile   searchLen-by-2 real -- the full profile for both hypotheses, returned
%                       so a caller can see the margin and the sidelobe structure rather than
%                       only the winner. An acquisition that wins by 1% is not an acquisition
%
%TWO HYPOTHESES, BECAUSE N_ID,2 IS PART OF WHAT IS BEING FOUND
%---------------------------------------------------------------
%The S-PSS sequence depends on N_ID,2^SL, so timing and that half of the identity are acquired
%together -- there is no "find the timing first, then read the identity". Correlating against
%one hypothesis only finds half the cells and, worse, finds the WRONG timing for the other half
%by locking onto a sidelobe.
%
%This is a time-domain correlation against the S-PSS as it appears after OFDM modulation, so
%the reference is generated by modulating a grid containing only the S-PSS. Correlating against
%the frequency-domain sequence directly would require the timing that is being searched for.

if searchLen < 1
    error('rx:sync:pssSearch:badSearchLen', 'pssSearch: searchLen must be >= 1, got %d', searchLen);
end

corrProfile = zeros(searchLen, 2);
refs = cell(1, 2);
for h = 1:2
    refs{h} = localPssReference(h - 1, mu, nSubcarriers);
end
refLen = numel(refs{1});

if numel(waveform) < refLen
    error('rx:sync:pssSearch:waveformTooShort', 'pssSearch: the waveform is %d samples but one S-PSS reference is %d', numel(waveform), refLen);
end

% The reference spans the WHOLE S-SSB block duration but is non-zero only in the two S-PSS
% symbols, so the correlation is taken over that support alone -- and the segment is normalised
% over the same support. Normalising by the whole segment's energy instead would divide a
% two-symbol correlation by a thirteen-symbol norm, depressing the peak to roughly sqrt(2/13)
% and burying it in the sidelobes of a noisy search. The peak then lands on the BLOCK start,
% which is the timing a caller wants, rather than on the first S-PSS symbol.
for h = 1:2
    ref  = refs{h};
    mask = abs(ref) > 0;
    refMasked = ref(mask);
    refNorm = max(norm(refMasked), eps);
    for n = 1:searchLen
        lo = n;
        hi = n + refLen - 1;
        if hi > numel(waveform)
            break;
        end
        seg = waveform(lo:hi);
        segMasked = seg(mask);
        corrProfile(n, h) = abs(refMasked' * segMasked) / (refNorm * max(norm(segMasked), eps));
    end
end

[peakPerHyp, offsetPerHyp] = max(corrProfile, [], 1);
[peak, hyp] = max(peakPerHyp);
NID2 = hyp - 1;
timingOffset = offsetPerHyp(hyp) - 1;
end

% =========================================================================
function ref = localPssReference(NID2, mu, nSubcarriers)
%localPssReference The S-PSS as it appears in the time domain, for one N_ID,2 hypothesis.
%Built by placing the sequence on an otherwise empty grid and OFDM modulating it, so the
%reference carries the same cyclic prefix and pulse shape the transmitter produced.
Nsymb = 13;
blockGrid = complex(zeros(132, Nsymb));
ind = phy.ts38211.slSPSSIndices();
seq = phy.ts38211.slSPSS(NID2);
blockGrid(sub2ind(size(blockGrid), ind(:, 1) + 1, ind(:, 2) + 1)) = [seq; seq];

grid = complex(zeros(nSubcarriers, Nsymb));
nCopy = min(132, nSubcarriers);
grid(1:nCopy, :) = blockGrid(1:nCopy, :);

% NOT trimmed to the non-zero span: the reference keeps the full block duration so that a
% correlation peak identifies the START OF THE BLOCK directly. Trimming to the S-PSS symbols
% would make the peak land on symbol 1 instead, and the caller would have to add back a CP-aware
% offset that depends on numerology -- precisely the kind of numerology-dependent constant
% .claude/rules/portability.md exists to keep out of call sites.
[ref, ~] = phy.lib.ofdmMod(grid, mu, 0);
end
